repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.20.0
    hooks:
      - id: mypy
        name: mypy (project venv)
        entry: ./.venv/bin/mypy --config-file=./pyproject.toml --show-traceback .
        language: system
        types: [ python ]
        verbose: true
        require_serial: true
        pass_filenames: false

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.9
    hooks:
      - id: ruff-check
        name: ruff check (project venv)
        entry: ./.venv/bin/ruff check --fix .
        language: system
        pass_filenames: false

      - id: ruff-format
        name: ruff format (project venv)
        entry: ./.venv/bin/ruff format .
        language: system
        pass_filenames: false

  - repo: local
    hooks:
      - id: dotenv-check
        name: dotenv-check
        entry: ./.venv/bin/python env_file_validator.py
        language: system
        always_run: true
        pass_filenames: false
