[SERVICE]
    Flush        1
    Parsers_File parsers.conf

[INPUT]
    Name   gelf
    Listen 0.0.0.0
    Port   12201
    Mode   udp

[FILTER]
    Name         parser
    Match        *
    Key_Name     log
    Parser       python_logs
    Reserve_Data On

[OUTPUT]
    Name            opensearch
    Match           *
    Host            ....
    Port            ....
    HTTP_User       ....
    HTTP_Passwd     ....
    Index           discount-system-logs
    tls             On
    tls.verify      Off
    Suppress_Type_Name On