[PARSER]
    Name        python_logs
    Format      regex
    # LOG_FORMAT:
    # 1. [%(asctime)s] -> (?<time>[^\]]+)
    # 2. [%(levelname)s] -> (?<level>[^\]]+)
    # 3. [%(filename)s:%(lineno)s %(threadName)s] -> (?<file>[^:]+):(?<line>\d+) (?<thread>[^\]]+)
    # 4. [%(name)s] -> (?<logger>[^\]]+)
    # 5. [%(message)s] -> (?<message>.*)
    Regex       ^\[(?<time>[^\]]+)\] \[(?<level>[^\]]+)\] \[(?<file>[^:]+):(?<line>\d+) (?<thread>[^\]]+)\] \[(?<logger>[^\]]+)\] \[(?<message>.*)\]$
    Time_Key    time
    Time_Format %Y-%m-%d %H:%M:%S