from enum import StrEnum


class RepositoriesErrorCodes(StrEnum):
    CATEGORY_IS_NOT_FOUND = "CATEGORY_IS_NOT_FOUND"
    DISCOUNTED_PRODUCT_IS_NOT_FOUND = "DISCOUNTED_PRODUCT_IS_NOT_FOUND"
    RETAILER_IS_NOT_FOUND = "RETAILER_IS_NOT_FOUND"
