# Generated by Django 6.0 on 2025-12-23 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategoryModel",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("category_uuid", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=64, unique=True)),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
                "db_table": "categories",
            },
        ),
        migrations.CreateModel(
            name="RetailerModel",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("retailer_uuid", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=64, unique=True)),
                ("url", models.URLField(max_length=2048)),
                ("phone_number", models.CharField(max_length=64)),
            ],
            options={
                "verbose_name": "retailer",
                "verbose_name_plural": "retailers",
                "db_table": "retailers",
            },
        ),
        migrations.CreateModel(
            name="CategoryHelperWordsModel",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("word", models.CharField(max_length=64, unique=True)),
                (
                    "category",
                    models.ForeignKey(
                        db_column="category_uuid",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="discount_service.categorymodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "category helper word",
                "verbose_name_plural": "category helper words",
                "db_table": "category_helper_words",
            },
        ),
        migrations.CreateModel(
            name="DiscountedProductModel",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("discounted_product_uuid", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("real_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("discounted_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("name", models.CharField(max_length=64, unique=True)),
                ("url", models.URLField(max_length=2048)),
                (
                    "category",
                    models.ForeignKey(
                        db_column="category_uuid",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="discount_service.categorymodel",
                    ),
                ),
                (
                    "retailer",
                    models.ForeignKey(
                        db_column="retailer_uuid",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="discount_service.retailermodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "discounted product",
                "verbose_name_plural": "discounted products",
                "db_table": "discounted_products",
            },
        ),
    ]
