# Generated by Django 6.0.2 on 2026-02-14 16:30
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("discount_service", "0001_initial"),
    ]

    operations = [
        TrigramExtension(),
    ]
