# Generated by Django 6.0 on 2026-01-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discount_service", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DiscountedProductReadModel",
        ),
        migrations.AlterField(
            model_name="discountedproductmodel",
            name="created_at",
            field=models.DateTimeField(),
        ),
    ]
