# Generated by Django 6.0.2 on 2026-02-14 16:40

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("discount_service", "0002_auto_20260214_1630"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="categoryhelperwordsmodel",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["word"], name="helper_word_trgm_idx", opclasses=["gin_trgm_ops"]
            ),
        ),
    ]
