[PARSER]
    Name         metax_python_parser
    Format       regex
    Regex        ^\[(?<log_time>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2})\] \[(?<level>[^\]]+)\] \[(?<request_id>[^\]]*)\] \[pid=(?<pid>\d+) (?<process_name>[^\]]+)\] \[(?<file>[^:]+):(?<line>\d+) (?<thread>[^\]]+)\] \[(?<logger_name>[^\]]+)\] \[(?<message>.*)\]$
    Time_Key     log_time
    Time_Format  %Y-%m-%d %H:%M:%S
    Types        pid:integer line:integer