# Generated by Django 6.0.4 on 2026-05-06 16:40

import django.db.models.deletion
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategoryModel",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now()),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now()),
                ),
                ("uuid", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=64, unique=True)),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
                "db_table": "categories",
            },
        ),
        migrations.CreateModel(
            name="RetailerModel",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now()),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now()),
                ),
                ("uuid", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        choices=[("yerevan-city", "yerevan-city"), ("sas-am", "sas-am")],
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("home_page_url", models.URLField(max_length=2048)),
                ("phone_number", models.CharField(max_length=64)),
            ],
            options={
                "verbose_name": "retailer",
                "verbose_name_plural": "retailers",
                "db_table": "retailers",
            },
        ),
        migrations.CreateModel(
            name="TaskiqModel",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now()),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now()),
                ),
                ("task_id", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("task_name", models.CharField(max_length=255)),
                ("request_id", models.CharField(blank=True, db_index=True, default="", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("STARTED", "Started"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "taskiq_tasks",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="CategoryHelperWordsModel",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now()),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now()),
                ),
                ("uuid", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("helper_word_text", models.CharField(max_length=128, unique=True)),
                (
                    "category",
                    models.ForeignKey(
                        db_column="category_uuid",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="metax.categorymodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "category helper word",
                "verbose_name_plural": "category helper words",
                "db_table": "category_helper_words",
            },
        ),
        migrations.CreateModel(
            name="DiscountedProductModel",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now()),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_default=django.db.models.functions.datetime.Now()),
                ),
                ("uuid", models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ("real_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("discounted_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("name", models.CharField(max_length=128)),
                ("url", models.URLField(max_length=2048)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        db_column="category_uuid",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="metax.categorymodel",
                    ),
                ),
                (
                    "retailer",
                    models.ForeignKey(
                        db_column="retailer_uuid",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="metax.retailermodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "discounted product",
                "verbose_name_plural": "discounted products",
                "db_table": "discounted_products",
            },
        ),
    ]
