# Generated by Django 6.0.3 on 2026-03-29 16:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("metax", "0002_retailer_name_enum_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discountedproductmodel",
            name="name",
            field=models.CharField(max_length=128),
        ),
    ]
