# Generated by Django 6.0.5 on 2026-06-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metax', '0002_seed_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountedproductmodel',
            name='name_translit',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
