# Generated by Django 6.0.5 on 2026-07-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metax', '0002_seed_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retailermodel',
            name='name',
            field=models.CharField(choices=[('yerevan-city', 'yerevan-city'), ('sas-am', 'sas-am'), ('tntesakan-am', 'tntesakan-am'), ('rouge-am', 'rouge-am')], max_length=64, unique=True),
        ),
    ]
