# Generated by Django 6.0.5 on 2026-06-28 14:48

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metax', '0003_discountedproductmodel_name_translit'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='discountedproductmodel',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name_translit'], name='dp_name_translit_trgm_gin', opclasses=['gin_trgm_ops']),
        ),
    ]
