# Generated by Django 6.0.5 on 2026-07-02 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metax', '0003_seed_category_examples'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailermodel',
            name='default_category',
            field=models.ForeignKey(blank=True, db_column='default_category_uuid', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='metax.categorymodel'),
        ),
        migrations.AlterField(
            model_name='retailermodel',
            name='name',
            field=models.CharField(choices=[('yerevan-city', 'yerevan-city'), ('sas-am', 'sas-am'), ('tntesakan-am', 'tntesakan-am')], max_length=64, unique=True),
        ),
    ]
